name: Keep Render Service Awake

on:
  schedule:
    - cron: "*/5 * * * *" # chạy mỗi 5 phút (UTC)
  workflow_dispatch: # vẫn cho phép bấm chạy tay

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render /ping
        run: |
          curl -fsS https://voice-app-be.onrender.com/ping || echo "Ping failed"
